# The main entry point of workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

# source config variables
configfile: "config/config.yaml"

########## RULES ##########
### first rule is downloading gtex rna-seq data (gene tpm)
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

rule download_rnaseq:
    input:
        HTTP.remote(os.path.join(config["host"], config["rnaseq_file"]), keep_local=True)
    output:
        os.path.join("resources", config["rnaseq_file"])
    shell:
        "mv {input} {output}" #snakemake automatically creates missing directories

### second rule is downloading gtex annotation file
from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider

HTTP = HTTPRemoteProvider()

rule download_annotations:
    input:
        HTTP.remote(os.path.join(config["host"], config["annotations_file"]), keep_local=True)
    output:
        os.path.join("resources", config["annotations_file"])
    shell:
        "mv {input} {output}"

### third rule is obtaining a dictionary of tissues from annotation files
rule tissues_dictionary:
    input:
        os.path.join("resources", config["annotations_file"])
    output:
        "results/gtex_tissues_dictionary.csv"
    script:
        "scripts/generate-tissues-dictionary.py"

### third rule is selecting samples from a tissue from gene files
rule select_samples:
    input:
        tissues_dict="results/gtex_tissues_dictionary.csv",
        rnaseq_data=os.path.join("resources", config["rnaseq_file"])
    output:
